apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ln6p7qly7-nodejs 
  janus-idp.io/tekton: ln6p7qly7-nodejs
  backstage.io/kubernetes-id: ln6p7qly7-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ln6p7qly7-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml