apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ln6p7qly7-nodejs
  janus-idp.io/tekton: ln6p7qly7-nodejs
  backstage.io/kubernetes-id: ln6p7qly7-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ln6p7qly7-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
