apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ln6p7qly7-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ln6p7qly7-nodejs 
  name: ln6p7qly7-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ln6p7qly7-nodejs 
